[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-cloudflare-cache-purge"
