[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
package = "netlify-plugin-sitemap"

  [plugins.inputs]
  prettyURLs = true      # Optional, for prettier URLs without file extensions
